//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class api_bug
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public api_bug()
        {
            this.api_commentbug = new HashSet<api_commentbug>();
            this.task_bugcomment = new HashSet<task_bugcomment>();
        }
    
        public int bug_id { get; set; }
        public Nullable<int> project_id { get; set; }
        public Nullable<int> service_id { get; set; }
        public Nullable<int> task_id { get; set; }
        public string bug_name { get; set; }
        public string des { get; set; }
        public Nullable<int> status { get; set; }
        public string keyword { get; set; }
        public string url_file { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public Nullable<int> is_important { get; set; }
        public Nullable<bool> is_view_test { get; set; }
        public Nullable<bool> is_view_work { get; set; }
        public Nullable<bool> is_overtime { get; set; }
        public Nullable<System.DateTime> start_overtime { get; set; }
        public Nullable<System.DateTime> end_overtime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<api_commentbug> api_commentbug { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<task_bugcomment> task_bugcomment { get; set; }
    }
}
