//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class api_plugin
    {
        public int plugin_id { get; set; }
        public int category_id { get; set; }
        public string plugin_name { get; set; }
        public string des { get; set; }
        public string images { get; set; }
        public string file_url { get; set; }
        public string keywords { get; set; }
        public string is_url { get; set; }
        public Nullable<bool> is_app { get; set; }
        public int is_order { get; set; }
        public Nullable<bool> status { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string title { get; set; }
    
        public virtual api_category api_category { get; set; }
    }
}
