//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class backup_schedule
    {
        public string backup_id { get; set; }
        public string title { get; set; }
        public Nullable<int> type_backup { get; set; }
        public Nullable<System.DateTime> time_backup { get; set; }
        public Nullable<int> type_time_backup { get; set; }
        public Nullable<int> time_backup_week { get; set; }
        public Nullable<int> time_backup_month { get; set; }
        public string folder_backup_path { get; set; }
        public Nullable<int> type_path_backup { get; set; }
        public Nullable<int> type_path_backup_other { get; set; }
        public Nullable<bool> is_active { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public Nullable<int> organization_id { get; set; }
    }
}
