//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class birthday_cmt
    {
        public int id { get; set; }
        public string contents { get; set; }
        public string image { get; set; }
        public string receive_user { get; set; }
        public string created_by { get; set; }
        public string created_ip { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_token_ip { get; set; }
        public string paths { get; set; }
    }
}
