//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class calendar_duty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public calendar_duty()
        {
            this.calendar_duty_coincide = new HashSet<calendar_duty_coincide>();
            this.calendar_duty_person = new HashSet<calendar_duty_person>();
            this.calendar_duty_procedure = new HashSet<calendar_duty_procedure>();
            this.calendar_duty_sign = new HashSet<calendar_duty_sign>();
            this.calendar_duty_signuser = new HashSet<calendar_duty_signuser>();
        }
    
        public string calendar_duty_id { get; set; }
        public Nullable<int> is_timelot { get; set; }
        public Nullable<System.DateTime> date_timelot { get; set; }
        public string boardroom_id { get; set; }
        public string place_name { get; set; }
        public string contents { get; set; }
        public string contents_en { get; set; }
        public string note { get; set; }
        public Nullable<int> is_type_send { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> is_order { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_ip { get; set; }
        public string modified_token_id { get; set; }
        public Nullable<int> organization_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<calendar_duty_coincide> calendar_duty_coincide { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<calendar_duty_person> calendar_duty_person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<calendar_duty_procedure> calendar_duty_procedure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<calendar_duty_sign> calendar_duty_sign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<calendar_duty_signuser> calendar_duty_signuser { get; set; }
    }
}
