//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class calendar_duty_sunday
    {
        public int key_id { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> week { get; set; }
        public string user_id { get; set; }
        public string note { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modify_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string modify_ip { get; set; }
        public string modify_token_id { get; set; }
        public Nullable<int> organization_id { get; set; }
    }
}
