//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat_logs
    {
        public int log_id { get; set; }
        public string chat_group_id { get; set; }
        public string chat_message_id { get; set; }
        public Nullable<int> organization_id { get; set; }
        public string des { get; set; }
        public string message { get; set; }
        public Nullable<int> receiver { get; set; }
        public Nullable<int> log_type { get; set; }
        public Nullable<bool> is_view { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
    
        public virtual chat_group chat_group { get; set; }
    }
}
