//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat_member
    {
        public string chat_member_id { get; set; }
        public string chat_group_id { get; set; }
        public string user_join { get; set; }
        public Nullable<System.DateTime> date_join { get; set; }
        public Nullable<System.DateTime> date_out { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> number_not_seen { get; set; }
        public Nullable<bool> is_captain { get; set; }
        public Nullable<bool> is_notify { get; set; }
        public Nullable<System.DateTime> date_delete { get; set; }
        public string last_message_id { get; set; }
        public Nullable<System.DateTime> last_seen_date { get; set; }
    
        public virtual chat_group chat_group { get; set; }
    }
}
