//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_slideshow_image
    {
        public int image_id { get; set; }
        public int slideshow_id { get; set; }
        public string image_name { get; set; }
        public string des { get; set; }
        public string is_filepath { get; set; }
        public string is_link { get; set; }
        public bool status { get; set; }
        public Nullable<bool> is_video { get; set; }
        public int is_order { get; set; }
        public string is_poster { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
    
        public virtual cms_slideshow cms_slideshow { get; set; }
    }
}
