//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_news
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cms_news()
        {
            this.cms_news_users = new HashSet<cms_news_users>();
        }
    
        public int news_id { get; set; }
        public Nullable<int> topic_id { get; set; }
        public Nullable<int> organization_id { get; set; }
        public string relate_id { get; set; }
        public Nullable<int> lang_id { get; set; }
        public Nullable<int> news_type { get; set; }
        public Nullable<bool> is_hot { get; set; }
        public string news_name { get; set; }
        public string image { get; set; }
        public string contents { get; set; }
        public string details { get; set; }
        public string keywords { get; set; }
        public string author { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> is_visitor { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> is_order { get; set; }
        public string censor { get; set; }
        public Nullable<System.DateTime> date_censor { get; set; }
        public string ip_censor { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
    
        public virtual cms_topic cms_topic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms_news_users> cms_news_users { get; set; }
    }
}
