//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class config_groups
    {
        public int config_groups_id { get; set; }
        public string groups_name { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> config_groups_type { get; set; }
        public Nullable<int> confirm_type { get; set; }
        public Nullable<bool> is_created_back { get; set; }
        public Nullable<bool> is_default { get; set; }
        public Nullable<bool> is_department { get; set; }
        public Nullable<bool> is_auto_confirm { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<bool> status { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
    }
}
