//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class decision_appoint
    {
        public int appoint_id { get; set; }
        public Nullable<int> decision_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> work_position_id { get; set; }
        public Nullable<int> position_id { get; set; }
        public string contract_id { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
