//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class device_inventory_personnel
    {
        public int inventory_personnel_id { get; set; }
        public int inventory_details_id { get; set; }
        public int inventory_slip_id { get; set; }
        public string user_id { get; set; }
        public string avatar { get; set; }
        public string full_name { get; set; }
        public string position_name { get; set; }
        public string organization_name { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<System.DateTime> date_reviews { get; set; }
        public string reviews { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<bool> is_approved { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
    }
}
