//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class device_provider
    {
        public int provider_id { get; set; }
        public string provider_name { get; set; }
        public Nullable<bool> type { get; set; }
        public string address { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public string fax { get; set; }
        public string website { get; set; }
        public string tax_code { get; set; }
        public string bank_account_number { get; set; }
        public string bank_name { get; set; }
        public string vocative { get; set; }
        public string full_name { get; set; }
        public string position { get; set; }
        public string contact_address { get; set; }
        public string phone_number { get; set; }
        public string contact_email { get; set; }
        public int organization_id { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> is_order { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
    }
}
