//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class device_process_log
    {
        public int process_log_id { get; set; }
        public int device_note_id { get; set; }
        public Nullable<int> device_process_id { get; set; }
        public Nullable<int> device_process_type { get; set; }
        public string content { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<bool> is_process { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
    }
}
