//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class device_handover
    {
        public int handover_id { get; set; }
        public Nullable<int> organization_id { get; set; }
        public string organization_name { get; set; }
        public string handover_number { get; set; }
        public Nullable<System.DateTime> handover_created_date { get; set; }
        public string user_deliver_id { get; set; }
        public string user_deliver_name { get; set; }
        public string user_deliver_position { get; set; }
        public Nullable<int> user_deliver_department_id { get; set; }
        public string user_deliver_department_name { get; set; }
        public string user_verifier_id { get; set; }
        public string user_verifier_name { get; set; }
        public string user_verifier_position { get; set; }
        public Nullable<int> user_verifier_department_id { get; set; }
        public string user_verifier_department_name { get; set; }
        public string user_receiver_id { get; set; }
        public string user_receiver_name { get; set; }
        public string user_receiver_position { get; set; }
        public Nullable<int> user_receiver_department_id { get; set; }
        public string user_receiver_department_name { get; set; }
        public Nullable<int> handover_type { get; set; }
        public Nullable<System.DateTime> confirmation_date { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<bool> is_cancel { get; set; }
        public Nullable<int> receiver_department { get; set; }
        public Nullable<bool> is_receiver_department { get; set; }
        public string user_cancel_id { get; set; }
        public Nullable<System.DateTime> cancel_date { get; set; }
        public Nullable<int> proposal_id { get; set; }
        public Nullable<int> receipt_type { get; set; }
        public Nullable<System.DateTime> receiver_date { get; set; }
        public Nullable<bool> is_receiver_accept { get; set; }
        public Nullable<int> device_repair_id { get; set; }
        public Nullable<System.DateTime> verifier_date { get; set; }
        public Nullable<bool> is_verifier_accept { get; set; }
        public string user_confirmation_id { get; set; }
        public Nullable<bool> is_individual { get; set; }
        public string print_note { get; set; }
        public Nullable<int> device_department_id { get; set; }
        public Nullable<int> is_order { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
    }
}
