//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class device_card
    {
        public int card_id { get; set; }
        public string proposal_code { get; set; }
        public int device_id { get; set; }
        public string device_name { get; set; }
        public string device_des { get; set; }
        public string image { get; set; }
        public string device_number { get; set; }
        public string barcode_id { get; set; }
        public Nullable<int> barcode_type { get; set; }
        public string barcode_image { get; set; }
        public string device_unit { get; set; }
        public Nullable<int> device_type_id { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
        public Nullable<System.DateTime> use_date { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> depreciation_month { get; set; }
        public Nullable<int> insurance_month { get; set; }
        public Nullable<int> insurance_cycle { get; set; }
        public string manufacture_country { get; set; }
        public Nullable<int> manufacture_year { get; set; }
        public string producer { get; set; }
        public string warranty_company { get; set; }
        public string warranty_company_address { get; set; }
        public string warranty_contact { get; set; }
        public string warranty_phone { get; set; }
        public string device_note { get; set; }
        public string status { get; set; }
        public string old_status { get; set; }
        public Nullable<System.DateTime> fix_date { get; set; }
        public string assets_condition { get; set; }
        public Nullable<double> current_price { get; set; }
        public Nullable<int> device_department_id { get; set; }
        public string device_user_id { get; set; }
        public Nullable<int> provider_id { get; set; }
        public Nullable<int> warehouse_id { get; set; }
        public Nullable<int> warehouse_id_old { get; set; }
        public Nullable<int> corporation { get; set; }
        public string device_area { get; set; }
        public Nullable<int> manage_department_id { get; set; }
        public Nullable<bool> confirmed { get; set; }
        public Nullable<bool> issued { get; set; }
        public Nullable<int> organization_id { get; set; }
        public Nullable<bool> is_recall { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
        public Nullable<bool> is_insurance { get; set; }
        public string nearest_user { get; set; }
        public string check_recall { get; set; }
        public Nullable<int> import_batch { get; set; }
        public Nullable<int> import_year { get; set; }
        public string dispatch_number { get; set; }
        public Nullable<int> device_manufacturer_id { get; set; }
    
        public virtual device_main device_main { get; set; }
        public virtual device_type device_type { get; set; }
    }
}
