//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class device_user_follows
    {
        public int user_follows_id { get; set; }
        public int device_process_id { get; set; }
        public Nullable<int> organization_id { get; set; }
        public string user_id { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<int> user_fllows_type { get; set; }
        public string device_number_code { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
    }
}
