//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class device_approved_group
    {
        public int approved_group_id { get; set; }
        public Nullable<int> organization_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<bool> status { get; set; }
        public string approved_group_code { get; set; }
        public string approved_group_name { get; set; }
        public Nullable<bool> is_default { get; set; }
        public string classify { get; set; }
        public string module { get; set; }
        public Nullable<int> approved_type { get; set; }
        public Nullable<bool> is_approved_by_department { get; set; }
        public Nullable<bool> is_return_created { get; set; }
        public Nullable<bool> is_suggest_repair { get; set; }
        public Nullable<int> assessed_property_type { get; set; }
        public Nullable<bool> repair_property_assessment { get; set; }
        public Nullable<bool> is_skip { get; set; }
        public Nullable<bool> suggest_price { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
    }
}
