//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class device_inventory_slip
    {
        public int inventory_slip_id { get; set; }
        public int organization_id { get; set; }
        public string inventory_number { get; set; }
        public Nullable<System.DateTime> inventory_date { get; set; }
        public Nullable<int> is_type { get; set; }
        public string inventory_user_id { get; set; }
        public Nullable<System.DateTime> inventory_created_date { get; set; }
        public Nullable<bool> completed_status { get; set; }
        public Nullable<System.DateTime> completed_date { get; set; }
        public Nullable<int> status { get; set; }
        public string pkk_status { get; set; }
        public Nullable<int> approved_group_id { get; set; }
        public string approved_user_id { get; set; }
        public Nullable<int> is_return { get; set; }
        public Nullable<System.DateTime> date_return { get; set; }
        public Nullable<System.DateTime> confirmation_date { get; set; }
        public Nullable<int> is_order { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
        public string warehouse_id { get; set; }
        public string department_id { get; set; }
        public string deviceFrom { get; set; }
    }
}
