//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class device_recall
    {
        public int device_recall_id { get; set; }
        public string recall_number { get; set; }
        public string created_place { get; set; }
        public string content_recall { get; set; }
        public string reason { get; set; }
        public string user_collector { get; set; }
        public string stocker { get; set; }
        public string product_user_position { get; set; }
        public string user_warehouse_position { get; set; }
        public int warehouse_id { get; set; }
        public string product_user { get; set; }
        public string print_note { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> recall_created_date { get; set; }
        public Nullable<System.DateTime> confirmation_date { get; set; }
        public Nullable<int> organization_id { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
        public Nullable<int> is_return { get; set; }
        public Nullable<System.DateTime> date_return { get; set; }
    }
}
