//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class device_handover_attach
    {
        public int handover_attach_id { get; set; }
        public Nullable<int> organization_id { get; set; }
        public int handover_id { get; set; }
        public Nullable<int> card_id { get; set; }
        public string device_name { get; set; }
        public string serial { get; set; }
        public Nullable<int> device_id { get; set; }
        public string condition { get; set; }
        public string note { get; set; }
        public string user_id { get; set; }
        public Nullable<bool> is_purchase { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> is_order { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
        public string device_number { get; set; }
        public string barcode_id { get; set; }
        public string device_unit { get; set; }
        public Nullable<int> repair_details_id { get; set; }
    }
}
