//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_reservation_number
    {
        public int reservation_number_id { get; set; }
        public int organization_id { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> nav_type { get; set; }
        public Nullable<int> doc_group_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> organization_config_id { get; set; }
        public string reservation_code { get; set; }
        public bool is_private { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
        public bool is_used { get; set; }
    }
}
