//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_follows
    {
        public string follow_id { get; set; }
        public Nullable<int> organization_id { get; set; }
        public Nullable<int> doc_master_id { get; set; }
        public Nullable<int> send_by { get; set; }
        public string send_by_name { get; set; }
        public Nullable<System.DateTime> send_date { get; set; }
        public Nullable<int> receive_by { get; set; }
        public string receive_by_name { get; set; }
        public Nullable<int> receive_type { get; set; }
        public Nullable<int> receive_last_group_user { get; set; }
        public Nullable<System.DateTime> view_date { get; set; }
        public Nullable<System.DateTime> deadline_date { get; set; }
        public string follow_parent_id { get; set; }
        public Nullable<int> level { get; set; }
        public Nullable<bool> is_inworkflow { get; set; }
        public Nullable<int> workflow_id { get; set; }
        public Nullable<int> workflow_group_id { get; set; }
        public string doc_status_id { get; set; }
        public string parent_doc_status_id { get; set; }
        public string message { get; set; }
        public Nullable<bool> flash_sign { get; set; }
        public Nullable<bool> esim_sign { get; set; }
        public Nullable<bool> is_prioritized { get; set; }
        public bool is_return { get; set; }
        public Nullable<bool> is_stamped { get; set; }
        public Nullable<System.DateTime> stamped_date { get; set; }
        public bool is_recall { get; set; }
        public string recall_message { get; set; }
        public Nullable<System.DateTime> recall_date { get; set; }
        public Nullable<bool> is_signed { get; set; }
        public Nullable<bool> is_completed { get; set; }
        public string completed_message { get; set; }
        public Nullable<System.DateTime> completed_date { get; set; }
        public Nullable<bool> is_main_completed { get; set; }
        public int is_order { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
        public Nullable<int> department_user_approval { get; set; }
        public string concat_name { get; set; }
    
        public virtual doc_master doc_master { get; set; }
    }
}
