//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_completed_confirms
    {
        public int completed_confirm_id { get; set; }
        public Nullable<int> doc_master_id { get; set; }
        public Nullable<int> follow_id { get; set; }
        public Nullable<int> sent_by { get; set; }
        public Nullable<System.DateTime> sent_date { get; set; }
        public string sent_message { get; set; }
        public Nullable<int> approved_by { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
        public string approved_message { get; set; }
        public Nullable<bool> is_agreed { get; set; }
        public Nullable<int> is_order { get; set; }
    
        public virtual doc_master doc_master { get; set; }
    }
}
