//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_connect
    {
        public int doc_connect_id { get; set; }
        public Nullable<int> doc_master_id { get; set; }
        public string organization_connect_id { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> is_type { get; set; }
        public int type_export { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_ip { get; set; }
        public string modified_token_id { get; set; }
    
        public virtual doc_organization_connect doc_organization_connect { get; set; }
    }
}
