//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_workflow_groups
    {
        public int workflow_group_id { get; set; }
        public Nullable<int> workflow_id { get; set; }
        public Nullable<int> role_group_id { get; set; }
        public Nullable<int> return_group_id { get; set; }
        public Nullable<int> return_type { get; set; }
        public Nullable<int> foward_type { get; set; }
        public int is_order { get; set; }
    
        public virtual doc_workflows doc_workflows { get; set; }
    }
}
