//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_codes_use
    {
        public int code_use_id { get; set; }
        public Nullable<int> organization_id { get; set; }
        public string code_master_id { get; set; }
        public Nullable<int> doc_group_id { get; set; }
        public Nullable<int> dispatch_book_id { get; set; }
    
        public virtual doc_codes_master doc_codes_master { get; set; }
    }
}
