//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_ca_issue_places
    {
        public int issue_place_id { get; set; }
        public string issue_place_name { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> organization_id { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
        public Nullable<int> parent_id { get; set; }
        public int level { get; set; }
        public string static_code { get; set; }
        public string dynamic_code { get; set; }
        public string search_code { get; set; }
        public string display_code { get; set; }
        public Nullable<bool> is_slider { get; set; }
        public bool is_online { get; set; }
        public Nullable<bool> is_system { get; set; }
    }
}
