//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_file_search
    {
        public int file_search_id { get; set; }
        public Nullable<int> doc_master_id { get; set; }
        public string file_content_text { get; set; }
    
        public virtual doc_master doc_master { get; set; }
    }
}
