//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class file_folder_share_user
    {
        public int folder_share_user { get; set; }
        public string folder_id { get; set; }
        public string user_id { get; set; }
        public string created_by { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    
        public virtual file_folder file_folder { get; set; }
    }
}
