//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class file_log
    {
        public int file_log_id { get; set; }
        public Nullable<int> file_id { get; set; }
        public string folder_id { get; set; }
        public string contents { get; set; }
        public string user_id { get; set; }
        public string full_name { get; set; }
        public int log_type { get; set; }
        public Nullable<bool> is_view { get; set; }
        public Nullable<System.DateTime> date_view { get; set; }
        public string date_string { get; set; }
        public Nullable<int> count_view_file { get; set; }
        public Nullable<int> count_download_file { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
        public string name { get; set; }
    }
}
