//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class file_folder_share
    {
        public int folder_share_id { get; set; }
        public string folder_id { get; set; }
        public string user_id { get; set; }
        public Nullable<int> organization_id { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<bool> is_read { get; set; }
        public Nullable<bool> is_edit { get; set; }
        public Nullable<bool> is_delete { get; set; }
        public Nullable<int> is_order { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
    
        public virtual file_folder file_folder { get; set; }
    }
}
