//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class file_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public file_info()
        {
            this.file_info_share = new HashSet<file_info_share>();
        }
    
        public int file_id { get; set; }
        public string folder_id { get; set; }
        public string file_name { get; set; }
        public string is_filepath { get; set; }
        public string name_file { get; set; }
        public string path_folder { get; set; }
        public Nullable<double> capacity { get; set; }
        public Nullable<bool> is_public { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<bool> is_image { get; set; }
        public string keywords { get; set; }
        public bool status { get; set; }
        public Nullable<int> views { get; set; }
        public Nullable<int> download { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
        public string module_key { get; set; }
        public string file_type { get; set; }
        public string id_key { get; set; }
        public Nullable<int> doc_type { get; set; }
    
        public virtual file_folder file_folder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<file_info_share> file_info_share { get; set; }
    }
}
