//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_profile_experience
    {
        public string profile_experience_id { get; set; }
        public string profile_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string company { get; set; }
        public string address { get; set; }
        public string title { get; set; }
        public string role { get; set; }
        public string wage { get; set; }
        public string reference_name { get; set; }
        public string reference_phone { get; set; }
        public string description { get; set; }
        public string reason { get; set; }
        public Nullable<int> is_order { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
    
        public virtual hrm_profile hrm_profile { get; set; }
    }
}
