//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hrm_contract()
        {
            this.hrm_allowance = new HashSet<hrm_allowance>();
        }
    
        public string contract_id { get; set; }
        public string profile_id { get; set; }
        public string contract_code { get; set; }
        public Nullable<int> contract_no { get; set; }
        public string contract_name { get; set; }
        public Nullable<int> type_contract_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> title_id { get; set; }
        public Nullable<int> work_position_id { get; set; }
        public Nullable<int> position_id { get; set; }
        public string professional_works { get; set; }
        public string employment { get; set; }
        public string description { get; set; }
        public Nullable<int> formality_id { get; set; }
        public Nullable<int> personel_groups_id { get; set; }
        public Nullable<int> personnel_level_id { get; set; }
        public Nullable<int> wage_type { get; set; }
        public Nullable<double> wage { get; set; }
        public Nullable<int> wage_id { get; set; }
        public Nullable<double> wage_level { get; set; }
        public Nullable<System.DateTime> wage_start_date { get; set; }
        public Nullable<System.DateTime> wage_end_date { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.DateTime> sign_date { get; set; }
        public string sign_user_id { get; set; }
        public string manager_user_id { get; set; }
        public string sign_address { get; set; }
        public string note { get; set; }
        public Nullable<bool> is_star { get; set; }
        public string liquidation_content { get; set; }
        public Nullable<System.DateTime> liquidation_date { get; set; }
        public Nullable<int> coef_salary_id { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> organization_id { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<bool> is_active { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_ip { get; set; }
        public string modified_token_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrm_allowance> hrm_allowance { get; set; }
        public virtual hrm_profile hrm_profile { get; set; }
    }
}
