//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_leave_profile
    {
        public int leave_profile_id { get; set; }
        public string profile_id { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<double> month1 { get; set; }
        public Nullable<double> month2 { get; set; }
        public Nullable<double> month3 { get; set; }
        public Nullable<double> month4 { get; set; }
        public Nullable<double> month5 { get; set; }
        public Nullable<double> month6 { get; set; }
        public Nullable<double> month7 { get; set; }
        public Nullable<double> month8 { get; set; }
        public Nullable<double> month9 { get; set; }
        public Nullable<double> month10 { get; set; }
        public Nullable<double> month11 { get; set; }
        public Nullable<double> month12 { get; set; }
        public Nullable<double> leave { get; set; }
        public Nullable<double> inventory { get; set; }
        public Nullable<double> bonus { get; set; }
        public Nullable<double> seniority { get; set; }
        public Nullable<int> organization_id { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_ip { get; set; }
        public string modified_token_id { get; set; }
    }
}
