//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_review_form_users
    {
        public int review_form_users_id { get; set; }
        public Nullable<int> review_form_id { get; set; }
        public string profile_id { get; set; }
        public string profile_code { get; set; }
        public string profile_user_name { get; set; }
        public string position_name { get; set; }
        public string department_name { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
