//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_config_contract_order
    {
        public int config_contract_order_id { get; set; }
        public Nullable<int> config_contract_id { get; set; }
        public string info_col { get; set; }
        public string separator { get; set; }
        public Nullable<int> order_type { get; set; }
        public int is_order { get; set; }
        public Nullable<bool> is_used { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
    }
}
