//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_profile_skill
    {
        public string profile_skill_id { get; set; }
        public string profile_id { get; set; }
        public string university_name { get; set; }
        public string branch { get; set; }
        public Nullable<int> specialized { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> form_traning_id { get; set; }
        public Nullable<System.DateTime> degree_date { get; set; }
        public string rating { get; set; }
        public Nullable<System.DateTime> graduation_year { get; set; }
        public Nullable<int> academic_level_id { get; set; }
        public Nullable<bool> is_man_degree { get; set; }
        public Nullable<int> certificate_id { get; set; }
        public Nullable<System.DateTime> certificate_start_date { get; set; }
        public Nullable<System.DateTime> certificate_end_date { get; set; }
        public string certificate_key_code { get; set; }
        public string certificate_version { get; set; }
        public string certificate_release_time { get; set; }
        public string file_name { get; set; }
        public Nullable<double> file_size { get; set; }
        public string file_type { get; set; }
        public Nullable<int> is_order { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
    }
}
