//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_ca_civil_servant_rank
    {
        public int civil_servant_rank_id { get; set; }
        public Nullable<int> wage_groups_id { get; set; }
        public string civil_servant_rank_code { get; set; }
        public string civil_servant_rank_name { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<bool> status { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
        public Nullable<int> organization_id { get; set; }
        public Nullable<bool> is_system { get; set; }
    
        public virtual hrm_ca_wage_groups hrm_ca_wage_groups { get; set; }
    }
}
