//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_insurance_resolve
    {
        public string insurance_resolve_id { get; set; }
        public string insurance_id { get; set; }
        public string profile_id { get; set; }
        public string type_mode { get; set; }
        public Nullable<System.DateTime> received_file_date { get; set; }
        public Nullable<System.DateTime> completed_date { get; set; }
        public Nullable<System.DateTime> received_money_date { get; set; }
        public Nullable<int> money { get; set; }
        public Nullable<int> is_order { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
    
        public virtual hrm_insurance hrm_insurance { get; set; }
    }
}
