//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_profile_relative
    {
        public string profile_relative_id { get; set; }
        public string profile_id { get; set; }
        public string relative_name { get; set; }
        public Nullable<int> is_type { get; set; }
        public Nullable<int> relationship_id { get; set; }
        public string birthday { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string countryside { get; set; }
        public string occupation { get; set; }
        public string company { get; set; }
        public string organization { get; set; }
        public string tax_code { get; set; }
        public string identification_citizen { get; set; }
        public Nullable<System.DateTime> identification_date_issue { get; set; }
        public string identification_place_issue { get; set; }
        public Nullable<int> is_dependent { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string info { get; set; }
        public string note { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<bool> is_root { get; set; }
        public Nullable<int> is_bout { get; set; }
        public Nullable<bool> is_company { get; set; }
        public Nullable<bool> is_die { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
    
        public virtual hrm_profile hrm_profile { get; set; }
    }
}
