//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_allowance_detail
    {
        public int detail_id { get; set; }
        public string allowance_id { get; set; }
        public string contract_id { get; set; }
        public Nullable<int> allowance_formality_id { get; set; }
        public string allowance_formality { get; set; }
        public Nullable<int> allowance_wage_id { get; set; }
        public string allowance_wage { get; set; }
        public Nullable<double> money { get; set; }
        public Nullable<int> is_type { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> is_order { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_ip { get; set; }
        public string modified_token_id { get; set; }
    
        public virtual hrm_allowance hrm_allowance { get; set; }
    }
}
