//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_ca_leaving_reason
    {
        public int leaving_reason_id { get; set; }
        public string leaving_reason_name { get; set; }
        public string symbol { get; set; }
        public Nullable<int> max_day { get; set; }
        public Nullable<int> unit { get; set; }
        public Nullable<int> is_payroll { get; set; }
        public Nullable<int> is_active { get; set; }
        public string description { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<bool> status { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
        public Nullable<int> organization_id { get; set; }
        public Nullable<bool> is_system { get; set; }
    }
}
