//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_profile_header
    {
        public int profile_header_id { get; set; }
        public string profile_header_name { get; set; }
        public Nullable<int> profile_header_value { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<int> organization_id { get; set; }
    }
}
