//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_config_insurance_rate
    {
        public int insurance_rate_id { get; set; }
        public string insurance_rate_name { get; set; }
        public Nullable<System.DateTime> from_month { get; set; }
        public Nullable<int> ins_premium { get; set; }
        public Nullable<int> social_ins_percent { get; set; }
        public Nullable<int> social_ins_company { get; set; }
        public Nullable<int> social_ins_employee { get; set; }
        public Nullable<int> accident_ins_percent { get; set; }
        public Nullable<int> accident_ins_company { get; set; }
        public Nullable<int> accident_ins_employee { get; set; }
        public Nullable<int> health_ins_percent { get; set; }
        public Nullable<int> health_ins_company { get; set; }
        public Nullable<int> health_ins_employee { get; set; }
        public Nullable<int> unemployment_ins_percent { get; set; }
        public Nullable<int> unemployment_ins_company { get; set; }
        public Nullable<int> unemployment_ins_employee { get; set; }
        public Nullable<int> organization_id { get; set; }
        public Nullable<bool> is_auto { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<bool> status { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
    }
}
