//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_work_schedule
    {
        public int work_schedule_id { get; set; }
        public string profile_id { get; set; }
        public Nullable<int> declare_shift_id { get; set; }
        public string declare_shift_name { get; set; }
        public string config_work_location_name { get; set; }
        public Nullable<int> config_work_location_id { get; set; }
        public Nullable<int> work_schedule_type { get; set; }
        public string work_schedule_years { get; set; }
        public string work_schedule_months { get; set; }
        public string work_schedule_days { get; set; }
        public Nullable<bool> is_full_time { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<int> organization_id { get; set; }
        public Nullable<bool> status { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
        public Nullable<bool> is_system { get; set; }
    }
}
