//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_decision_allowace
    {
        public int allowance_id { get; set; }
        public Nullable<int> wage_id { get; set; }
        public Nullable<int> level_id { get; set; }
        public Nullable<int> coef_salary_id { get; set; }
        public Nullable<int> allowance_formality_id { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
