//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_ca_management_major
    {
        public int management_major_id { get; set; }
        public Nullable<int> review_form_id { get; set; }
        public string management_major_name { get; set; }
        public string management_major_results { get; set; }
        public Nullable<bool> is_plan { get; set; }
        public Nullable<bool> is_results { get; set; }
        public Nullable<int> management_major_weight { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<bool> status { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
        public Nullable<int> organization_id { get; set; }
        public Nullable<bool> is_system { get; set; }
    }
}
