//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_rec_candidate
    {
        public int rec_candidate_id { get; set; }
        public int rec_calendar_id { get; set; }
        public string candidate_code { get; set; }
        public string full_name { get; set; }
        public string phone_number { get; set; }
        public Nullable<System.DateTime> time_recruitment { get; set; }
        public Nullable<int> organization_id { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<bool> status { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public Nullable<int> candidate_id { get; set; }
    }
}
