//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hrm_profile()
        {
            this.hrm_contract = new HashSet<hrm_contract>();
            this.hrm_profile_clan_history = new HashSet<hrm_profile_clan_history>();
            this.hrm_profile_edit = new HashSet<hrm_profile_edit>();
            this.hrm_profile_experience = new HashSet<hrm_profile_experience>();
            this.hrm_profile_health = new HashSet<hrm_profile_health>();
            this.hrm_profile_relate = new HashSet<hrm_profile_relate>();
            this.hrm_profile_relative = new HashSet<hrm_profile_relative>();
            this.hrm_profile_status = new HashSet<hrm_profile_status>();
            this.hrm_profile_tags = new HashSet<hrm_profile_tags>();
            this.hrm_profile_receipt = new HashSet<hrm_profile_receipt>();
        }
    
        public string profile_id { get; set; }
        public string profile_code { get; set; }
        public Nullable<int> profile_no { get; set; }
        public Nullable<int> superior_no { get; set; }
        public int key_id { get; set; }
        public string profile_user_name { get; set; }
        public string profile_nick_name { get; set; }
        public string profile_name { get; set; }
        public string profile_name_en { get; set; }
        public string profile_last_name { get; set; }
        public string avatar { get; set; }
        public string check_in_id { get; set; }
        public string superior_id { get; set; }
        public Nullable<System.DateTime> recruitment_date { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<int> gender { get; set; }
        public Nullable<int> birthplace_id { get; set; }
        public string birthplace_name { get; set; }
        public Nullable<int> birthplace_origin_id { get; set; }
        public string birthplace_origin_name { get; set; }
        public string place_register_permanent_first { get; set; }
        public Nullable<int> place_register_permanent { get; set; }
        public string place_register_permanent_name { get; set; }
        public Nullable<int> identity_papers_id { get; set; }
        public string identity_papers_code { get; set; }
        public Nullable<System.DateTime> identity_papers_outdate { get; set; }
        public Nullable<System.DateTime> identity_date_issue { get; set; }
        public Nullable<System.DateTime> identity_end_date_issue { get; set; }
        public Nullable<int> identity_place_id { get; set; }
        public Nullable<int> nationality_id { get; set; }
        public Nullable<int> marital_status { get; set; }
        public Nullable<int> ethnic_id { get; set; }
        public Nullable<int> religion_id { get; set; }
        public string tax_code { get; set; }
        public string bank_number { get; set; }
        public string bank_account { get; set; }
        public Nullable<int> bank_id { get; set; }
        public Nullable<int> cultural_level_id { get; set; }
        public string cultural_level_max { get; set; }
        public Nullable<int> academic_level_id { get; set; }
        public Nullable<int> political_theory_id { get; set; }
        public Nullable<int> specialization_id { get; set; }
        public Nullable<int> language_level_id { get; set; }
        public Nullable<int> informatic_level_id { get; set; }
        public Nullable<int> management_state_id { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string bike_code { get; set; }
        public string car_code { get; set; }
        public string place_permanent { get; set; }
        public string place_residence { get; set; }
        public Nullable<int> place_residence_id { get; set; }
        public string place_residence_name { get; set; }
        public string involved_name { get; set; }
        public string involved_place { get; set; }
        public string involved_phone { get; set; }
        public Nullable<int> relationship_id { get; set; }
        public string bevy_code { get; set; }
        public Nullable<System.DateTime> bevy_date { get; set; }
        public string bevy_address { get; set; }
        public string bevy_position { get; set; }
        public string civil_servant_rank_name { get; set; }
        public Nullable<bool> is_partisan { get; set; }
        public string card_partisan { get; set; }
        public Nullable<System.DateTime> partisan_date { get; set; }
        public Nullable<System.DateTime> partisan_main_date { get; set; }
        public string partisan_address { get; set; }
        public Nullable<double> partisan_fee { get; set; }
        public string partisan_branch { get; set; }
        public string partisan_official { get; set; }
        public Nullable<System.DateTime> partisan_joindate { get; set; }
        public Nullable<System.DateTime> organization_joindate { get; set; }
        public string organization_task { get; set; }
        public string appellation { get; set; }
        public string armorial { get; set; }
        public Nullable<System.DateTime> military_start_date { get; set; }
        public Nullable<System.DateTime> military_end_date { get; set; }
        public string military_rank { get; set; }
        public string military_title { get; set; }
        public string military_forte { get; set; }
        public string military_health { get; set; }
        public string military_reward { get; set; }
        public string military_discipline { get; set; }
        public string military_veterans_rank { get; set; }
        public string military_policy_family { get; set; }
        public Nullable<int> seniority_year { get; set; }
        public Nullable<int> seniority_month { get; set; }
        public string family_member { get; set; }
        public Nullable<System.DateTime> recruitment_date_first { get; set; }
        public string recruitment_form { get; set; }
        public string job_before_recruitment { get; set; }
        public string recruitment_position { get; set; }
        public Nullable<bool> is_re_recruitment { get; set; }
        public Nullable<int> recruitment_number { get; set; }
        public Nullable<System.DateTime> re_recruitment_date { get; set; }
        public string re_recruitment_form { get; set; }
        public string job_before_re_recruitment { get; set; }
        public string re_recruitment_position { get; set; }
        public string task_longest { get; set; }
        public string mission_forte { get; set; }
        public Nullable<double> salary_family { get; set; }
        public Nullable<double> salary_orther { get; set; }
        public string type_rent { get; set; }
        public Nullable<double> area_level { get; set; }
        public string type_house { get; set; }
        public Nullable<double> area_buy { get; set; }
        public Nullable<double> area_granted { get; set; }
        public Nullable<double> area_buy_yourself { get; set; }
        public Nullable<double> area_manufacture { get; set; }
        public string sign_address { get; set; }
        public Nullable<System.DateTime> sign_date { get; set; }
        public string biography_first { get; set; }
        public string biography_second { get; set; }
        public string biography_third { get; set; }
        public string file_name { get; set; }
        public string file_type { get; set; }
        public Nullable<double> file_size { get; set; }
        public Nullable<System.DateTime> file_modified_date { get; set; }
        public string file_modified_by { get; set; }
        public string profile_relative_id { get; set; }
        public string profile_skill_id { get; set; }
        public string profile_clan_history_id { get; set; }
        public string profile_experience_id { get; set; }
        public string note { get; set; }
        public Nullable<bool> is_star { get; set; }
        public Nullable<int> organization_id { get; set; }
        public Nullable<int> is_order { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> receipt_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrm_contract> hrm_contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrm_profile_clan_history> hrm_profile_clan_history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrm_profile_edit> hrm_profile_edit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrm_profile_experience> hrm_profile_experience { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrm_profile_health> hrm_profile_health { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrm_profile_relate> hrm_profile_relate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrm_profile_relative> hrm_profile_relative { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrm_profile_status> hrm_profile_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrm_profile_tags> hrm_profile_tags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrm_profile_receipt> hrm_profile_receipt { get; set; }
    }
}
