//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_config_usercode
    {
        public int usercode_id { get; set; }
        public string organization_name { get; set; }
        public string symbol { get; set; }
        public Nullable<int> length { get; set; }
        public Nullable<int> initialization { get; set; }
        public Nullable<bool> automatic { get; set; }
        public Nullable<int> organization_type { get; set; }
        public Nullable<int> parent_id { get; set; }
        public int organization_id { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<bool> status { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
    
        public virtual sys_organization sys_organization { get; set; }
    }
}
