//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_recruitment_proposal
    {
        public int recruitment_proposal_id { get; set; }
        public string recruitment_proposal_name { get; set; }
        public string recruitment_proposal_reason { get; set; }
        public Nullable<int> work_position_id { get; set; }
        public Nullable<int> position_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<bool> until_enough { get; set; }
        public Nullable<int> exist_personnel { get; set; }
        public Nullable<int> quantity_margin { get; set; }
        public Nullable<int> recruits_num { get; set; }
        public Nullable<int> formality_id { get; set; }
        public string workplace { get; set; }
        public Nullable<double> rec_salary_from { get; set; }
        public Nullable<double> rec_salary_to { get; set; }
        public Nullable<int> can_academic_level_id { get; set; }
        public Nullable<int> can_specialization_id { get; set; }
        public Nullable<int> can_experience_id { get; set; }
        public Nullable<int> can_language_level_id { get; set; }
        public Nullable<int> can_age_from { get; set; }
        public Nullable<int> can_age_to { get; set; }
        public Nullable<int> can_gender { get; set; }
        public Nullable<int> can_height_from { get; set; }
        public Nullable<int> can_height_to { get; set; }
        public Nullable<int> can_weight_from { get; set; }
        public Nullable<int> can_weight_to { get; set; }
        public string job_description { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<int> status { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
        public Nullable<int> organization_id { get; set; }
    }
}
