//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_config_contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hrm_config_contract()
        {
            this.hrm_config_contract_symbol = new HashSet<hrm_config_contract_symbol>();
        }
    
        public int config_contract_id { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> initialization_number { get; set; }
        public Nullable<bool> auto_increment { get; set; }
        public Nullable<int> organization_id { get; set; }
        public int is_order { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrm_config_contract_symbol> hrm_config_contract_symbol { get; set; }
    }
}
