//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_config_contract_symbol
    {
        public int config_contract_symbol_id { get; set; }
        public Nullable<int> config_contract_id { get; set; }
        public Nullable<int> type_contract_id { get; set; }
        public string symbol { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
    
        public virtual hrm_ca_type_contract hrm_ca_type_contract { get; set; }
        public virtual hrm_config_contract hrm_config_contract { get; set; }
    }
}
