//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_payroll
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hrm_payroll()
        {
            this.hrm_payroll_user = new HashSet<hrm_payroll_user>();
        }
    
        public int payroll_id { get; set; }
        public string payroll_name { get; set; }
        public Nullable<int> declare_paycheck_id { get; set; }
        public Nullable<int> payroll_month { get; set; }
        public Nullable<int> payroll_year { get; set; }
        public Nullable<System.DateTime> sign_date { get; set; }
        public string sign_user { get; set; }
        public string profile_sign_id { get; set; }
        public Nullable<bool> is_approved { get; set; }
        public string list_profile_id { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<int> organization_id { get; set; }
        public Nullable<bool> status { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
        public string payroll_config { get; set; }
        public Nullable<int> report_key { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrm_payroll_user> hrm_payroll_user { get; set; }
    }
}
