//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_reward
    {
        public int reward_id { get; set; }
        public string reward_name { get; set; }
        public Nullable<int> reward_type { get; set; }
        public Nullable<int> reward_level_id { get; set; }
        public Nullable<int> reward_title_id { get; set; }
        public string reward_content { get; set; }
        public string reward_number { get; set; }
        public Nullable<System.DateTime> decision_date { get; set; }
        public Nullable<System.DateTime> effective_date { get; set; }
        public Nullable<double> reward_cost { get; set; }
        public Nullable<int> organization_id { get; set; }
        public Nullable<int> is_order { get; set; }
        public string reward_note { get; set; }
        public Nullable<int> status { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
        public string signer { get; set; }
        public string decision_place { get; set; }
    }
}
