//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_config_contact
    {
        public int config_contact_id { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<int> male_retirement { get; set; }
        public Nullable<int> female_retirement { get; set; }
        public bool is_date_of_birth { get; set; }
        public Nullable<bool> is_phone_number { get; set; }
        public Nullable<int> organization_id { get; set; }
        public int is_order { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
    }
}
