//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_campaign
    {
        public int campaign_id { get; set; }
        public string campaign_name { get; set; }
        public string campaign_code { get; set; }
        public Nullable<bool> is_recruitment_proposal { get; set; }
        public Nullable<int> recruitment_proposal_id { get; set; }
        public string user_verify { get; set; }
        public string user_follows { get; set; }
        public Nullable<int> num_vacancies { get; set; }
        public Nullable<double> expected_cost { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> rec_vacancies { get; set; }
        public Nullable<int> rec_position_id { get; set; }
        public Nullable<int> rec_formality_id { get; set; }
        public Nullable<double> rec_salary_from { get; set; }
        public string rec_workplace { get; set; }
        public Nullable<double> rec_salary_to { get; set; }
        public Nullable<System.DateTime> rec_recruitment_deadline { get; set; }
        public Nullable<int> rec_number_vacancies { get; set; }
        public Nullable<int> rec_candidate_sheet_id { get; set; }
        public Nullable<int> can_academic_level_id { get; set; }
        public Nullable<int> can_specialization_id { get; set; }
        public Nullable<int> can_experience_id { get; set; }
        public Nullable<int> can_language_level_id { get; set; }
        public Nullable<int> can_age_from { get; set; }
        public Nullable<int> can_age_to { get; set; }
        public Nullable<int> can_gender { get; set; }
        public Nullable<double> can_height_from { get; set; }
        public Nullable<double> can_height_to { get; set; }
        public Nullable<double> can_weight_to { get; set; }
        public Nullable<double> can_weight_from { get; set; }
        public string job_description { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> organization_id { get; set; }
        public Nullable<int> is_order { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_ip { get; set; }
        public string modified_token_id { get; set; }
    }
}
