//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_config_holidays
    {
        public int config_holidays_id { get; set; }
        public Nullable<int> title_id { get; set; }
        public Nullable<int> num_holidays { get; set; }
        public Nullable<int> num_seniority { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> organization_id { get; set; }
        public int is_order { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
    }
}
