//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_profile_assignment
    {
        public int assignment_id { get; set; }
        public string profile_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> title_id { get; set; }
        public Nullable<int> position_id { get; set; }
        public string professional_works { get; set; }
        public string description { get; set; }
        public string employment { get; set; }
        public Nullable<int> formality_id { get; set; }
        public Nullable<int> personel_groups_id { get; set; }
        public Nullable<int> personnel_level_id { get; set; }
        public string manager_user_id { get; set; }
        public Nullable<int> organization_id { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_main { get; set; }
        public Nullable<bool> is_experiment { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_ip { get; set; }
        public string modified_token_id { get; set; }
    }
}
