//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class law_documents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public law_documents()
        {
            this.law_comment = new HashSet<law_comment>();
            this.law_doc_related = new HashSet<law_doc_related>();
            this.law_doc_replace = new HashSet<law_doc_replace>();
            this.law_files = new HashSet<law_files>();
            this.law_logs = new HashSet<law_logs>();
            this.law_user_visitor = new HashSet<law_user_visitor>();
        }
    
        public string law_id { get; set; }
        public string law_name { get; set; }
        public string law_number { get; set; }
        public string law_type { get; set; }
        public string field_name { get; set; }
        public string user_signed { get; set; }
        public string summary { get; set; }
        public string tags { get; set; }
        public string publish_number { get; set; }
        public Nullable<System.DateTime> publish_date { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<int> is_new { get; set; }
        public string issue_place { get; set; }
        public Nullable<System.DateTime> issued_date { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_ip { get; set; }
        public string modified_token_id { get; set; }
        public Nullable<int> organization_id { get; set; }
        public Nullable<int> times_view { get; set; }
        public Nullable<int> times_download { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<law_comment> law_comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<law_doc_related> law_doc_related { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<law_doc_replace> law_doc_replace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<law_files> law_files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<law_logs> law_logs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<law_user_visitor> law_user_visitor { get; set; }
    }
}
