//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class law_files
    {
        public int file_id { get; set; }
        public string law_id { get; set; }
        public string file_name { get; set; }
        public string file_path { get; set; }
        public string file_path_temp { get; set; }
        public Nullable<double> file_size { get; set; }
        public string file_type { get; set; }
        public Nullable<int> law_file_type { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<bool> is_drafted { get; set; }
        public string message { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
    
        public virtual law_documents law_documents { get; set; }
    }
}
