//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class news_main
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public news_main()
        {
            this.news_comment = new HashSet<news_comment>();
        }
    
        public int news_id { get; set; }
        public Nullable<bool> is_comment { get; set; }
        public Nullable<int> news_type { get; set; }
        public Nullable<bool> is_hot { get; set; }
        public string title { get; set; }
        public string image { get; set; }
        public string des { get; set; }
        public string contents { get; set; }
        public string key_words { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string created_ip { get; set; }
        public string modified_ip { get; set; }
        public Nullable<int> is_visitor { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> is_order { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
        public string approved_ip { get; set; }
        public Nullable<bool> is_notify { get; set; }
        public string related_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> organization_id { get; set; }
        public string url_file { get; set; }
        public string file_type { get; set; }
        public Nullable<double> file_size { get; set; }
    
        public virtual news_category news_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<news_comment> news_comment { get; set; }
        public virtual sys_organization sys_organization { get; set; }
    }
}
