//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_main
    {
        public string project_id { get; set; }
        public string project_code { get; set; }
        public string project_name { get; set; }
        public string parent_id { get; set; }
        public Nullable<int> group_code { get; set; }
        public string description { get; set; }
        public string logo { get; set; }
        public Nullable<int> status { get; set; }
        public string keywords { get; set; }
        public Nullable<int> is_order { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_ip { get; set; }
        public string modified_token_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> organization_child_id { get; set; }
        public Nullable<int> organization_id { get; set; }
    
        public virtual task_ca_projectgroup task_ca_projectgroup { get; set; }
    }
}
