//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class request_sign_user
    {
        public string request_sign_user_id { get; set; }
        public string request_id { get; set; }
        public string user_id { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<int> is_type { get; set; }
        public Nullable<int> is_sign { get; set; }
        public Nullable<double> times_processing_max { get; set; }
        public Nullable<double> times_processing { get; set; }
        public Nullable<System.DateTime> sign_date { get; set; }
        public string sign_content { get; set; }
        public Nullable<System.DateTime> read_date { get; set; }
        public Nullable<bool> is_close { get; set; }
        public string description { get; set; }
        public Nullable<bool> is_notify { get; set; }
        public Nullable<bool> is_mail { get; set; }
        public Nullable<bool> is_forward { get; set; }
        public string device_id { get; set; }
        public Nullable<System.DateTime> device_date { get; set; }
        public Nullable<bool> is_app { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public Nullable<bool> is_app_modified { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_ip { get; set; }
        public string modified_token_id { get; set; }
        public Nullable<bool> is_app_send { get; set; }
        public string send_by { get; set; }
        public Nullable<System.DateTime> send_date { get; set; }
        public string send_ip { get; set; }
        public string send_token_id { get; set; }
    }
}
