//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class request_job_task
    {
        public string request_job_task_id { get; set; }
        public string request_job_id { get; set; }
        public string request_id { get; set; }
        public string request_relate_id { get; set; }
        public string task_id { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> is_type_job { get; set; }
        public Nullable<bool> is_app { get; set; }
        public string is_order { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
    }
}
