//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class request_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public request_master()
        {
            this.request_master_detail = new HashSet<request_master_detail>();
            this.request_master_file = new HashSet<request_master_file>();
            this.request_master_procedure = new HashSet<request_master_procedure>();
        }
    
        public string request_id { get; set; }
        public string request_name { get; set; }
        public string request_form_id { get; set; }
        public string request_team_id { get; set; }
        public string request_code { get; set; }
        public Nullable<int> request_number { get; set; }
        public Nullable<int> request_year { get; set; }
        public Nullable<double> times_processing_max { get; set; }
        public Nullable<double> times_processing { get; set; }
        public Nullable<int> priority_level { get; set; }
        public string content { get; set; }
        public Nullable<int> type_process { get; set; }
        public Nullable<bool> is_change_process { get; set; }
        public Nullable<bool> is_skip { get; set; }
        public Nullable<bool> is_notify_manager { get; set; }
        public Nullable<bool> is_private { get; set; }
        public Nullable<bool> is_evaluate { get; set; }
        public Nullable<bool> is_mail { get; set; }
        public Nullable<bool> is_sign_ca { get; set; }
        public Nullable<bool> is_general_request { get; set; }
        public Nullable<bool> is_security { get; set; }
        public Nullable<bool> is_overdue { get; set; }
        public Nullable<int> is_type_send { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_ip { get; set; }
        public string modified_token_id { get; set; }
        public Nullable<int> organization_id { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> status_processing { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
        public string completed_by { get; set; }
        public Nullable<System.DateTime> completed_date { get; set; }
        public Nullable<bool> is_delete { get; set; }
        public string evaluated_by { get; set; }
        public Nullable<System.DateTime> evaluated_date { get; set; }
        public string evaluated_content { get; set; }
        public Nullable<int> evaluated_score { get; set; }
        public string evaluated_ip { get; set; }
        public string evaluated_token_id { get; set; }
        public string completed_all_content { get; set; }
        public string completed_all_by { get; set; }
        public Nullable<System.DateTime> completed_all_date { get; set; }
        public string completed_all_ip { get; set; }
        public string completed_all_token_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<request_master_detail> request_master_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<request_master_file> request_master_file { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<request_master_procedure> request_master_procedure { get; set; }
    }
}
