//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class request_stick
    {
        public string request_stick_id { get; set; }
        public string request_comment_id { get; set; }
        public string request_id { get; set; }
        public Nullable<int> stick_id { get; set; }
        public Nullable<int> is_type { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
    
        public virtual request_comment request_comment { get; set; }
    }
}
