//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class request_setting
    {
        public string setting_id { get; set; }
        public Nullable<int> is_num_device { get; set; }
        public Nullable<bool> is_verify_sign { get; set; }
        public Nullable<bool> is_skip_web { get; set; }
        public Nullable<bool> is_one_device { get; set; }
        public Nullable<bool> is_creator_cancel_request { get; set; }
        public Nullable<bool> is_creator_del_request { get; set; }
        public Nullable<bool> is_creator_tag_follow { get; set; }
        public Nullable<bool> is_creator_handle { get; set; }
        public Nullable<bool> is_approved_cancel_request { get; set; }
        public Nullable<bool> is_approved_del_request { get; set; }
        public Nullable<bool> is_approved_tag_follow { get; set; }
        public Nullable<bool> is_approved_handle { get; set; }
        public Nullable<int> organization_id { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_ip { get; set; }
        public string modified_token_id { get; set; }
    }
}
