//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class request_ca_formd
    {
        public string request_formd_id { get; set; }
        public string request_form_id { get; set; }
        public string ten_truong { get; set; }
        public string kieu_truong { get; set; }
        public Nullable<int> is_length { get; set; }
        public int is_order { get; set; }
        public bool is_required { get; set; }
        public bool is_label { get; set; }
        public string is_parent_id { get; set; }
        public int is_type { get; set; }
        public string is_class { get; set; }
        public string tudien_id { get; set; }
        public string text_key { get; set; }
        public string value_key { get; set; }
        public Nullable<double> is_width { get; set; }
        public string text_align { get; set; }
        public Nullable<int> is_permission { get; set; }
        public Nullable<int> lv { get; set; }
    }
}
