//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class request_comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public request_comment()
        {
            this.request_stick = new HashSet<request_stick>();
        }
    
        public string request_comment_id { get; set; }
        public string request_id { get; set; }
        public string parent_id { get; set; }
        public string content { get; set; }
        public Nullable<int> is_type { get; set; }
        public Nullable<int> type_comment { get; set; }
        public Nullable<int> is_sign { get; set; }
        public Nullable<bool> is_delete { get; set; }
        public Nullable<bool> is_app { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<request_stick> request_stick { get; set; }
    }
}
