//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class request_ca_form
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public request_ca_form()
        {
            this.request_ca_form_sign = new HashSet<request_ca_form_sign>();
            this.request_ca_form_team = new HashSet<request_ca_form_team>();
        }
    
        public string request_form_id { get; set; }
        public string request_form_name { get; set; }
        public string request_form_code { get; set; }
        public string request_group_id { get; set; }
        public string description { get; set; }
        public Nullable<bool> is_notify_manage { get; set; }
        public Nullable<int> is_process { get; set; }
        public Nullable<int> time_max_process { get; set; }
        public Nullable<bool> is_review { get; set; }
        public Nullable<bool> is_use_all { get; set; }
        public Nullable<int> request_form_example_id { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<int> organization_id { get; set; }
        public Nullable<bool> is_private { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_ip { get; set; }
        public string modified_token_id { get; set; }
        public Nullable<bool> is_system { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<request_ca_form_sign> request_ca_form_sign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<request_ca_form_team> request_ca_form_team { get; set; }
    }
}
