//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class request_ca_form_sign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public request_ca_form_sign()
        {
            this.request_form_sign_user = new HashSet<request_form_sign_user>();
        }
    
        public string request_form_sign_id { get; set; }
        public string request_team_id { get; set; }
        public string request_form_id { get; set; }
        public string group_name { get; set; }
        public Nullable<int> type_process { get; set; }
        public Nullable<bool> is_skip_offline { get; set; }
        public Nullable<int> is_type_group { get; set; }
        public Nullable<bool> is_skip_group { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<bool> status { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
    
        public virtual request_ca_form request_ca_form { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<request_form_sign_user> request_form_sign_user { get; set; }
    }
}
