//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shows_main
    {
        public int shows_id { get; set; }
        public string path { get; set; }
        public string image { get; set; }
        public string file_name { get; set; }
        public string title { get; set; }
        public string link { get; set; }
        public string file_type { get; set; }
        public Nullable<double> file_size { get; set; }
        public Nullable<int> status { get; set; }
        public string created_by { get; set; }
        public string key_words { get; set; }
        public Nullable<bool> is_comment { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string created_ip { get; set; }
        public string modified_ip { get; set; }
        public Nullable<int> organization_id { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<int> is_visitor { get; set; }
        public string file_folder { get; set; }
    }
}
