//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class smart_report
    {
        public string report_id { get; set; }
        public string report_name { get; set; }
        public string report_group { get; set; }
        public string report_template { get; set; }
        public string report_config { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<bool> is_public { get; set; }
        public Nullable<bool> is_table { get; set; }
        public Nullable<bool> is_temp { get; set; }
        public string proc_name { get; set; }
        public string proc_get { get; set; }
        public string profile_id { get; set; }
        public string role_access { get; set; }
        public string user_access { get; set; }
        public string user_deny { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_ip { get; set; }
        public string modified_token_id { get; set; }
        public Nullable<int> organization_id { get; set; }
        public int report_key { get; set; }
    }
}
