//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_file_mapping
    {
        public string file_key_id { get; set; }
        public string file_id { get; set; }
        public string file_path { get; set; }
        public string file_name { get; set; }
        public Nullable<double> file_size { get; set; }
        public string file_title { get; set; }
        public string file_table { get; set; }
        public Nullable<int> type_path { get; set; }
        public string module_key { get; set; }
        public string role_access { get; set; }
        public string user_access { get; set; }
        public string deny_access { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
    }
}
