//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_organization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sys_organization()
        {
            this.device_main = new HashSet<device_main>();
            this.doc_codes = new HashSet<doc_codes>();
            this.doc_decision_forms = new HashSet<doc_decision_forms>();
            this.hrm_config_usercode = new HashSet<hrm_config_usercode>();
            this.news_main = new HashSet<news_main>();
            this.sys_modules = new HashSet<sys_modules>();
            this.sys_users_sub = new HashSet<sys_users_sub>();
            this.task_department_configuration = new HashSet<task_department_configuration>();
        }
    
        public int organization_id { get; set; }
        public string organization_key { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string listparent_id { get; set; }
        public string organization_name { get; set; }
        public string organization_name_en { get; set; }
        public string logo { get; set; }
        public string background_image { get; set; }
        public string is_url { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> organization_type { get; set; }
        public string text_color { get; set; }
        public string background_color { get; set; }
        public string short_name { get; set; }
        public string address { get; set; }
        public Nullable<double> coord_x { get; set; }
        public Nullable<double> coord_y { get; set; }
        public Nullable<int> place_id { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
        public string api_link { get; set; }
        public string file_link { get; set; }
        public string phone { get; set; }
        public string mail { get; set; }
        public string fax { get; set; }
        public string product_name { get; set; }
        public Nullable<double> data_organization { get; set; }
        public string department_doc_code { get; set; }
        public string user_receiver { get; set; }
        public string business_code { get; set; }
        public Nullable<System.DateTime> foundation_date { get; set; }
        public string mission { get; set; }
        public string description { get; set; }
        public string feature { get; set; }
        public Nullable<int> is_level { get; set; }
        public Nullable<System.DateTime> dissolution_date { get; set; }
        public string representative { get; set; }
        public string address_registration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<device_main> device_main { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_codes> doc_codes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_decision_forms> doc_decision_forms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrm_config_usercode> hrm_config_usercode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<news_main> news_main { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_modules> sys_modules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_users_sub> sys_users_sub { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<task_department_configuration> task_department_configuration { get; set; }
    }
}
