//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_token
    {
        public string token_id { get; set; }
        public string user_id { get; set; }
        public string full_name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public string from_device { get; set; }
        public string ip { get; set; }
    
        public virtual sys_users sys_users { get; set; }
    }
}
