//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_modules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sys_modules()
        {
            this.sys_role_modules = new HashSet<sys_role_modules>();
        }
    
        public int module_id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string module_name { get; set; }
        public string image { get; set; }
        public string icon { get; set; }
        public string is_link { get; set; }
        public string is_filepath { get; set; }
        public string is_stand { get; set; }
        public string is_target { get; set; }
        public int is_order { get; set; }
        public bool status { get; set; }
        public bool is_main { get; set; }
        public Nullable<int> organization_id { get; set; }
        public string is_size { get; set; }
        public Nullable<int> max_length_file { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
        public string module_key { get; set; }
        public string list_parent { get; set; }
        public Nullable<bool> is_view_parent { get; set; }
        public string report_code { get; set; }
        public string report_note { get; set; }
        public string permission { get; set; }
    
        public virtual sys_organization sys_organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_role_modules> sys_role_modules { get; set; }
    }
}
