//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_organization_merger
    {
        public int organization_merger_id { get; set; }
        public Nullable<int> organization_merged_id { get; set; }
        public Nullable<int> organization_receive_id { get; set; }
        public Nullable<int> organization_id { get; set; }
        public Nullable<int> organization_dissolution_id { get; set; }
        public Nullable<int> organization_dispatch_id { get; set; }
        public string decision_number { get; set; }
        public Nullable<System.DateTime> decision_date { get; set; }
        public string signer { get; set; }
        public Nullable<int> type { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
    }
}
