//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_role_modules
    {
        public int role_module_id { get; set; }
        public string role_id { get; set; }
        public string user_id { get; set; }
        public int module_id { get; set; }
        public Nullable<int> organization_id { get; set; }
        public string module_functions { get; set; }
        public int is_level { get; set; }
        public string is_permission { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
    
        public virtual sys_modules sys_modules { get; set; }
        public virtual sys_roles sys_roles { get; set; }
    }
}
