//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_functions_module
    {
        public int module_function_id { get; set; }
        public string module_key { get; set; }
        public string function_id { get; set; }
        public string function_name { get; set; }
        public string group_name { get; set; }
        public int is_order { get; set; }
        public bool is_status { get; set; }
    }
}
