//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_config_file_public
    {
        public long file_public_id { get; set; }
        public string table_name { get; set; }
        public string file_id { get; set; }
        public string file_name { get; set; }
        public string file_path { get; set; }
        public Nullable<int> type_public { get; set; }
        public Nullable<bool> is_admin_view { get; set; }
    }
}
