//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_logs
    {
        public int id { get; set; }
        public string title { get; set; }
        public string controller { get; set; }
        public Nullable<System.DateTime> log_date { get; set; }
        public string log_content { get; set; }
        public string full_name { get; set; }
        public string user_id { get; set; }
        public string token_id { get; set; }
        public string modified_ip { get; set; }
        public Nullable<int> is_type { get; set; }
        public string module { get; set; }
        public Nullable<int> status { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
        public string search_name { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_token_id { get; set; }
        public Nullable<int> log_type { get; set; }
    }
}
