//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_extend
    {
        public string extend_id { get; set; }
        public string task_id { get; set; }
        public Nullable<System.DateTime> current_end_date { get; set; }
        public Nullable<System.DateTime> extend_old_date { get; set; }
        public Nullable<System.DateTime> extend_new_date { get; set; }
        public string reason { get; set; }
        public Nullable<bool> is_agree { get; set; }
        public string answer { get; set; }
        public Nullable<System.DateTime> accept_date { get; set; }
        public string accept_user { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_ip { get; set; }
        public string modified_token_id { get; set; }
    
        public virtual task_origin task_origin { get; set; }
    }
}
