//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_person_report_processing
    {
        public int process_id { get; set; }
        public int report_id { get; set; }
        public Nullable<int> review_turn { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<int> group_role { get; set; }
        public string user_id { get; set; }
        public Nullable<int> is_step { get; set; }
        public Nullable<int> is_type { get; set; }
        public Nullable<int> user_point { get; set; }
        public string user_messages { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_ip { get; set; }
        public string modified_token_id { get; set; }
    }
}
