//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_bugcomment
    {
        public int bugcomment_id { get; set; }
        public Nullable<int> bug_id { get; set; }
        public string des { get; set; }
        public Nullable<int> status { get; set; }
        public string group_name { get; set; }
        public string check_by { get; set; }
        public Nullable<System.DateTime> check_date { get; set; }
        public string url_file { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_token_id { get; set; }
        public string created_ip { get; set; }
        public Nullable<System.DateTime> actual_date { get; set; }
        public Nullable<System.DateTime> finished_date { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<bool> is_add { get; set; }
        public Nullable<System.DateTime> switch_test_date { get; set; }
        public Nullable<bool> overtime { get; set; }
    
        public virtual api_bug api_bug { get; set; }
    }
}
