//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_follow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public task_follow()
        {
            this.task_follow_step = new HashSet<task_follow_step>();
        }
    
        public string follow_id { get; set; }
        public string task_id { get; set; }
        public string follow_name { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.DateTime> start_real_date { get; set; }
        public Nullable<System.DateTime> end_real_date { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<int> status { get; set; }
        public string created_by { get; set; }
        public string created_ip { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public string modified_ip { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public Nullable<bool> is_template { get; set; }
        public Nullable<int> process_time { get; set; }
        public string organization_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<task_follow_step> task_follow_step { get; set; }
        public virtual task_origin task_origin { get; set; }
    }
}
