//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_test
    {
        public int test_id { get; set; }
        public string test_group_id { get; set; }
        public int task_id { get; set; }
        public string test_user_id { get; set; }
        public Nullable<System.DateTime> test_date { get; set; }
        public string test_content { get; set; }
        public Nullable<bool> test_pass { get; set; }
        public string test_bugs { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public bool is_main { get; set; }
        public bool is_delete { get; set; }
    
        public virtual task_main task_main { get; set; }
    }
}
