//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_case
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public test_case()
        {
            this.test_times = new HashSet<test_times>();
        }
    
        public int case_id { get; set; }
        public string case_name { get; set; }
        public string project_id { get; set; }
        public string work_id { get; set; }
        public string keywords { get; set; }
        public string des { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<bool> is_pass { get; set; }
        public Nullable<int> test_number { get; set; }
        public Nullable<int> number_completed { get; set; }
        public Nullable<int> is_pass_step { get; set; }
        public string file_test { get; set; }
        public string code_test { get; set; }
        public Nullable<System.DateTime> date_test { get; set; }
        public string is_url { get; set; }
        public bool show_chrome { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<test_times> test_times { get; set; }
    }
}
