//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tivi_screen_propaganda
    {
        public string tivi_propaganda_id { get; set; }
        public string screen_id { get; set; }
        public string title { get; set; }
        public Nullable<int> type_data { get; set; }
        public Nullable<int> video_id { get; set; }
        public Nullable<int> shows_id { get; set; }
        public string link_folder { get; set; }
        public string link_org { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<int> organization_id { get; set; }
        public Nullable<bool> is_embeb { get; set; }
        public Nullable<int> number_slide { get; set; }
    
        public virtual tivi_screen_detail tivi_screen_detail { get; set; }
    }
}
