//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tivi_log
    {
        public int log_id { get; set; }
        public string tivi_id { get; set; }
        public Nullable<int> organization_id { get; set; }
        public string content { get; set; }
        public string action { get; set; }
        public string method { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_by { get; set; }
        public string created_token_id { get; set; }
    }
}
