//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tivi_screen_image
    {
        public string tivi_image_id { get; set; }
        public string screen_id { get; set; }
        public string file_name { get; set; }
        public string file_path { get; set; }
        public Nullable<double> file_size { get; set; }
        public string file_type { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<int> organization_id { get; set; }
        public string group_img { get; set; }
        public Nullable<bool> is_copy { get; set; }
    
        public virtual tivi_screen_detail tivi_screen_detail { get; set; }
    }
}
