//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tivi_screen_detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tivi_screen_detail()
        {
            this.tivi_screen_image = new HashSet<tivi_screen_image>();
            this.tivi_screen_propaganda = new HashSet<tivi_screen_propaganda>();
        }
    
        public string screen_id { get; set; }
        public string screen_name { get; set; }
        public string tivi_id { get; set; }
        public Nullable<bool> display_screen_calendar { get; set; }
        public Nullable<bool> display_screen_docs { get; set; }
        public Nullable<bool> display_screen_shows { get; set; }
        public Nullable<bool> display_screen_image { get; set; }
        public Nullable<bool> display_calendar_meeting { get; set; }
        public Nullable<bool> display_calendar_working { get; set; }
        public Nullable<bool> display_calendar_duty { get; set; }
        public Nullable<int> number_docs { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<int> calendar_department_id { get; set; }
        public Nullable<bool> is_change_shows { get; set; }
        public Nullable<int> time_change_shows { get; set; }
        public Nullable<bool> is_change_images { get; set; }
        public Nullable<int> time_change_images { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        public virtual tivi_screen tivi_screen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tivi_screen_image> tivi_screen_image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tivi_screen_propaganda> tivi_screen_propaganda { get; set; }
    }
}
