//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tivi_screen_config
    {
        public int tivi_screen_id { get; set; }
        public Nullable<int> organization_id { get; set; }
        public Nullable<int> docs_display_number { get; set; }
        public Nullable<int> time_change_screen { get; set; }
        public Nullable<bool> display_calendar_meeting { get; set; }
        public Nullable<bool> display_calendar_working { get; set; }
        public Nullable<bool> display_calendar_duty { get; set; }
        public Nullable<int> calendar_department_id { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public Nullable<int> is_order { get; set; }
    }
}
