//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tivi_screen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tivi_screen()
        {
            this.tivi_screen_detail = new HashSet<tivi_screen_detail>();
        }
    
        public string tivi_id { get; set; }
        public string tivi_name { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<bool> is_change_screen { get; set; }
        public Nullable<int> time_change_screen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tivi_screen_detail> tivi_screen_detail { get; set; }
    }
}
