//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trace
    {
        public int row_number { get; set; }
        public Nullable<int> event_class { get; set; }
        public string application_name { get; set; }
        public string nt_username { get; set; }
        public string login_name { get; set; }
        public Nullable<int> cpu { get; set; }
        public Nullable<long> reads { get; set; }
        public Nullable<long> writes { get; set; }
        public Nullable<long> duration { get; set; }
        public Nullable<int> client_process_id { get; set; }
        public Nullable<int> spid { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public byte[] binary_data { get; set; }
    }
}
